### ISSUE TITLE
Capabilities token case sensitive

### ISSUE THREAD

**Issue by gerome12** [OsiriX-Foundation/KheopsAuthorization#12]
Searches on the database are not case sensitive. But tokens are case sensitive.
So :
ssyF4OnRpCyMmejpvXYZEv
and
SSYF4ONRPCYMMEJPVXYZEV
are the same and both are valid. But these two tokens are completely different

**Comment by spalte** [comment]
Good catch!

**Comment by gerome12** [comment]
Solve with the postgresql database.
